### ISSUE TITLE
Организационна среща за дефиниране на задачи и триаж

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2017#1]
- [x] Избор на дата
- [x] Преглед на миналогодишни задачи 
- [x] Дефиниране на задачи
- [x] Триаж и разпределение

**Comment by krokodilerian** [comment]
Каква дата имаме да избираме?

**Comment by zeridon** [comment]
След като се видим с хората от тех парка ще трябва да си направим още една среща за да си напишем задачките и да се почват да се копат.
