### ISSUE TITLE
Планиране на деплоъмънта на сетъпа

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2017#10]
Стъпки етц

**Comment by zeridon** [comment]
@AgIt0 @Dragast имате ли някакви планове за разпъването или сме до "Кутии по зали"

**Comment by AgIt0** [comment]
Не разбирам въпроса нещо. Разпъването както миналата година поне по 1, който знае добре сетъпа отговаря за зала и насочва хората които му помагат(ако за това става дума).

**Comment by zeridon** [comment]
good enough
