### ISSUE TITLE
Да се подберат честотите за радиостанциите

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2017#12]
Подбор на честоти/канали и заделяне по функционалност (свързано с #11)

**Comment by lz1irq** [comment]
Можем да разделим комуникацията на следните канали:
* Видео
* Мрежа
* Общ

Не знам не-техническите екипи до каква степен ще имат нужда от радиовръзка, затова за момента ги слагам в един канал. Ще трябва на място да проверим какво е положението със заетостта на каналите и колко се чуваме ние навън/колко чуваме хора извън сградата, но мисля, че ще можем да намерим поне 3 свободни канала.
