### ISSUE TITLE
IRC/Slack Канали

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2017#18]
- [x] създаване на IRC канали (ако е необходимо)
 - [x] създаване на Slack канали
 - [x] Синхронизиране на информацията между каналите.
 - [x] Мигриране на matterbridge на eric

**Comment by zeridon** [comment]
За момента имаме следната конфигурация

| Slack | IRC |
|--------|-------|
| #general | #openfest |
| #noc | #of-noc |
| #video | #video |

**Comment by krokodilerian** [comment]
Видео хората искате ли си канал?

**Comment by lz1irq** [comment]
Те имат #video в Slack и IRC, трябва да се пусне bridge.

**Comment by zeridon** [comment]
Ще се правят ли отделни канали за 2те зали или който иска да се изсипва в #openfest

**Comment by krokodilerian** [comment]
Отделни канали има смисъл само ако има задаване на въпроси през irc. Не знам дали ще имаме хора за това тая година.

**Comment by zeridon** [comment]
вече е на ерик
