### ISSUE TITLE
Да се съберат SSH ключове на NOC

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2017#21]
- [x] @Arcopix 
- [x] @krokodilerian 
- [x] Тишо
- [x] @shteryana 
- [x] @zeridon
- [x] @lz1irq 
- [x] @tochev 
- [x] @robotpanic 
- [x] @Yasen6275

**Comment by lz1irq** [comment]
http://ivo.schupen.net/tardis.key

**Comment by krokodilerian** [comment]
https://vasil.ludost.net/maniax.key

**Comment by zeridon** [comment]
http://home.getoto.net/zeridon.keys

**Comment by Yasen6275** [comment]
http://bigbro.uni-sofia.bg/Yasen6275_1.key
http://bigbro.uni-sofia.bg/Yasen6275_2.key

**Comment by Arcopix** [comment]
https://load.devhex.org/key/stefan.key

**Comment by zeridon** [comment]
Ключовете са събрани и инсталирани на временния ерик (#7)

**Comment by robotpanic** [comment]
ключовете да се копират и на постоянния ерик от човек с достъп до временния ерик И постоянния ерик

**Comment by zeridon** [comment]
done
