### ISSUE TITLE
Call for hardware

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2017#3]
Необходима железария:

 - [x] 1x Core switch - 24p Gbit min preferred 48p - Cisco 3760
 - [x] 1x Team/noc switch - 24p Gbit min - Cisco 3570G
 - [x] 2x Videoteam switch - 10p gbit - TP-Link 3210SG
 - [x] 2x Workshop switch - 24p - Cisco 3550
 - [x] 1x Reception switch - 10p gbit - TP-Link 3210SG
 - [ ] 13x WiFi AP + 3x spare
    *  [x] - ap-cf-mr-1     -     Linksys WRT1900ACS	-   @hackman	    
    *  [ ] - ap-cf-mr-2     -     D-Link DAP-2695	    -   init Lab	   
    *  [ ] - ap-cf-mr-4     -     D-Link DAP-2695	    -   init Lab	    
    *  [x] - ap-cf-mr-3     -     Linksys WRT1900ACS	-   @hackman	    
    *  [x] - ap-cf-f-r      -     TP-Link Archer C5	    -   @hackman	    
    *  [x] - ap-cf-sr-1     -     TP-Link Archer C5	    -   Точо	        
    *  [x] - ap-cf-sr-2     -     TP-Link Archer C7	    -   @lz1irq	        
    *  [x] - ap-cf-f-l      -     TP-Link Archer C7	    -   @neterbg	     
    *  [x] - ap-cf-ch       -     TP-Link Archer C5	    -   @krokodilerian  
    *  [x] - ap-cf-qws      -     TP-Link Archer C5	    -   @Arcopix	    
    *  [x] - ap-ws-ws1      -     Linksys WRT1900ACS	-   @hackman	    
    *  [x] - ap-ws-ws2      -     TP-Link Archer C5	    -   @hackman	   
    *  [x] - ap-ws-noc      -     TP-Link Archer C5	    -   @hackman	    
    *  [ ] - spare          -     TP-Link Archer C5	    -   init Lab	   
    *  [x] - spare          -     TP-Link Archer C5	    -   @Arcopix   
    *  [x] - spare          -     TP-Link WDR4300	    -   @Arcopix	    

     

 - [x] PoE switch/spliter/injector ???
 - [x] 2x Monitor за NOC
 - [x] 2x Laptop за NOC
 - [x] 12+ Радиостанции

**Comment by lz1irq** [comment]
По груба преценка ще ни трябват 14 AP-та, като не съм сигурен дали в тази бройка влизат устройствата за legacy мрежата (изглежда ще имаме такава и тази година). Ще се постарая до края на седмицата да кажа точна бройка и може би разположение.

**Comment by Arcopix** [comment]
Може да разчитате на моите две AP-та (както обикновено)

**Comment by robotpanic** [comment]
Давам един Archer

**Comment by zeridon** [comment]
Радиостанциите се следят в #11 и #12

**Comment by neter-bg** [comment]
Един Archer C7 от мен

**Comment by shteryana** [comment]
Имам свободно apu3a4 (http://www.pcengines.ch/apu3a4.htm) с QCA9882 модул (http://www.pcengines.ch/wle600vx.htm)

**Comment by zeridon** [comment]
Финализирани са изискванията за желязо. Можем да минем с 24портов кор суич но предпочитам да е 48 за всеки случай

**Comment by lz1irq** [comment]
Сложил съм списък с AP-тата и от кого трябва да ги вземем. Хубаво е да почнем да ги събираме в лаба ~2 седмици преди събитието.

**Comment by eniac111** [comment]
Мога пак да взема моя монитор? 26"

Имам и няколко китайски 17"

**Comment by zeridon** [comment]
Отбелязани са switch-овете
