### ISSUE TITLE
IPv4 / IPv6 Свързаност/конфигуриране

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2017#30]
От къде ще дойде и с какви конфизи

**Comment by krokodilerian** [comment]
По принцип мисля да заделя /32 за феста, така и така ще са един тунел и една пряка връзка и ще напиша config-а както ми е вкъщи, quagga-та да слага src на route-овете. За v6 по принцип даваме /62 - wired, wireless и още нещо-там-имаше.

Предлагам да седнем и да напишем един ден config-а директно на ерик, щото той може да се подкара целия по принцип още от сега.

**Comment by zeridon** [comment]
Принципно да време му е че останаха 2 седмици.

**Comment by zeridon** [comment]
https://github.com/OpenFest/openfest-network-2017/tree/master/routing
