### ISSUE TITLE
Подготовка на eric за събитието

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2017#7]
Eric трябва да бъде почистен преди събитието

 - [x] update до нещо достатъчно прясно (напр. stretch)
 - [ ] snmptrapd - enable & start
 - [x] nagios3 - enable & start
 - [x] collectd - enable & start
 - [x] carbon-cache@a - clean /opt/graphite/storage leave db and index, enable & start
 - [x] carbon-aggregator@top - enable & start
 - [ ] arpwatch - clean logs, /var/lib/arpwatch, enable & start
 - [x] uwsgi - enable & start
 - [x] nginx - enable & start
 - [ ] php5-fpm - enable & start
 - [x] fcgiwrap.service, fcgiwrap.socket - enable & start
 - [x] grafana-server - enable & start, set default dashboard for Guests
 - [x] rsyslog - clean /opt/syslog, restart
 - [x] asterisk - enable & start
 - [x] mumble - enable & start

**Comment by Arcopix** [comment]
Upgraded on eric2 (eric.devhex.net):
-    apache2-utils (2.4.10-10+deb8u7 => 2.4.10-10+deb8u10)
-    apt (1.0.9.8.3 => 1.0.9.8.4)
-    apt-transport-https (1.0.9.8.3 => 1.0.9.8.4)
-    apt-utils (1.0.9.8.3 => 1.0.9.8.4)
-    base-files (8+deb8u6 => 8+deb8u9)
-    bash (4.3-11+b1 => 4.3-11+deb8u1)
-    bind9-host (9.9.5.dfsg-9+deb8u7 => 9.9.5.dfsg-9+deb8u14)
-    binutils (2.25-5 => 2.25-5+deb8u1)
-    ca-certificates (20141019+deb8u1 => 20141019+deb8u3)
-    collectd (5.5.2-1~bpo8+1 => 5.7.0-3~bpo8+1)
-    collectd-core (5.5.2-1~bpo8+1 => 5.7.0-3~bpo8+1)
-    collectd-utils (5.5.2-1~bpo8+1 => 5.7.0-3~bpo8+1)
-    curl (7.38.0-4+deb8u4 => 7.38.0-4+deb8u5)
-    dbus (1.8.20-0+deb8u1 => 1.8.22-0+deb8u1)
-    debconf (1.5.56 => 1.5.56+deb8u1)
-    debconf-i18n (1.5.56 => 1.5.56+deb8u1)
-    debian-archive-keyring (2014.3 => 2017.5~deb8u1)
-    debootstrap (1.0.67 => 1.0.67+deb8u1)
-    dnsutils (9.9.5.dfsg-9+deb8u7 => 9.9.5.dfsg-9+deb8u14)
-    e2fslibs (1.42.12-2 => 1.42.12-2+b1)
-    e2fsprogs (1.42.12-2 => 1.42.12-2+b1)
-    file (5.22+15-2+deb8u2 => 5.22+15-2+deb8u3)
-    git (2.1.4-2.1+deb8u2 => 2.1.4-2.1+deb8u4)
-    git-man (2.1.4-2.1+deb8u2 => 2.1.4-2.1+deb8u4)
-    gnupg (1.4.18-7+deb8u3 => 1.4.18-7+deb8u4)
-    gpgv (1.4.18-7+deb8u3 => 1.4.18-7+deb8u4)
-    grafana (3.1.1-1470047149 => 4.5.1)
-    host (9.9.5.dfsg-9+deb8u7 => 9.9.5.dfsg-9+deb8u14)
-    initramfs-tools (0.120+deb8u2 => 0.120+deb8u3)
-    intel-microcode (3.20160714.1~deb8u1 => 3.20170707.1~deb8u1)
-    libapt-inst1.5 (1.0.9.8.3 => 1.0.9.8.4)
-    libapt-pkg4.12 (1.0.9.8.3 => 1.0.9.8.4)
-    libbind9-90 (9.9.5.dfsg-9+deb8u7 => 9.9.5.dfsg-9+deb8u14)
-    libc-bin (2.19-18+deb8u6 => 2.19-18+deb8u10)
-    libc-dev-bin (2.19-18+deb8u6 => 2.19-18+deb8u10)
-    libc6 (2.19-18+deb8u6 => 2.19-18+deb8u10)
-    libc6-dev (2.19-18+deb8u6 => 2.19-18+deb8u10)
-    libc6-i386 (2.19-18+deb8u6 => 2.19-18+deb8u10)
-    libcairo2 (1.14.0-2.1+deb8u1 => 1.14.0-2.1+deb8u2)
-    libcomerr2 (1.42.12-2 => 1.42.12-2+b1)
-    libcurl3 (7.38.0-4+deb8u4 => 7.38.0-4+deb8u5)
-    libcurl3-gnutls (7.38.0-4+deb8u4 => 7.38.0-4+deb8u5)
-    libdbus-1-3 (1.8.20-0+deb8u1 => 1.8.22-0+deb8u1)
-    libdns-export100 (9.9.5.dfsg-9+deb8u7 => 9.9.5.dfsg-9+deb8u14)
-    libdns100 (9.9.5.dfsg-9+deb8u7 => 9.9.5.dfsg-9+deb8u14)
-    libevent-2.0-5 (2.0.21-stable-2 => 2.0.21-stable-2+deb8u1)
-    libexpat1 (2.1.0-6+deb8u3 => 2.1.0-6+deb8u4)
-    libexpat1-dev (2.1.0-6+deb8u3 => 2.1.0-6+deb8u4)
-    libffi-dev (3.1-2+b2 => 3.1-2+deb8u1)
-    libffi6 (3.1-2+b2 => 3.1-2+deb8u1)
-    libfreetype6 (2.5.2-3+deb8u1 => 2.5.2-3+deb8u2)
-    libgcrypt20 (1.6.3-2+deb8u2 => 1.6.3-2+deb8u4)
-    libgd3 (2.1.0-5+deb8u7 => 2.1.0-5+deb8u11)
-    libgdk-pixbuf2.0-0 (2.31.1-2+deb8u5 => 2.31.1-2+deb8u6)
-    libgdk-pixbuf2.0-common (2.31.1-2+deb8u5 => 2.31.1-2+deb8u6)
-    libgnutls-deb0-28 (3.3.8-6+deb8u3 => 3.3.8-6+deb8u7)
-    libgnutls-openssl27 (3.3.8-6+deb8u3 => 3.3.8-6+deb8u7)
-    libgraphite2-3 (1.3.6-1~deb8u1 => 1.3.10-1~deb8u1)
-    libgtk2.0-0 (2.24.25-3+deb8u1 => 2.24.25-3+deb8u2)
-    libgtk2.0-common (2.24.25-3+deb8u1 => 2.24.25-3+deb8u2)
-    libhogweed2 (2.7.1-5+deb8u1 => 2.7.1-5+deb8u2)
-    libicu52 (52.1-8+deb8u3 => 52.1-8+deb8u5)
-    libio-socket-ssl-perl (2.002-2+deb8u1 => 2.002-2+deb8u2)
-    libirs-export91 (9.9.5.dfsg-9+deb8u7 => 9.9.5.dfsg-9+deb8u14)
-    libisc-export95 (9.9.5.dfsg-9+deb8u7 => 9.9.5.dfsg-9+deb8u14)
-    libisc95 (9.9.5.dfsg-9+deb8u7 => 9.9.5.dfsg-9+deb8u14)
-    libisccc90 (9.9.5.dfsg-9+deb8u7 => 9.9.5.dfsg-9+deb8u14)
-    libisccfg-export90 (9.9.5.dfsg-9+deb8u7 => 9.9.5.dfsg-9+deb8u14)
-    libisccfg90 (9.9.5.dfsg-9+deb8u7 => 9.9.5.dfsg-9+deb8u14)
-    libjasper1 (1.900.1-debian1-2.4+deb8u1 => 1.900.1-debian1-2.4+deb8u3)
-    libldap-2.4-2 (2.4.40+dfsg-1+deb8u2 => 2.4.40+dfsg-1+deb8u3)
-    liblwres90 (9.9.5.dfsg-9+deb8u7 => 9.9.5.dfsg-9+deb8u14)
-    libmagic1 (5.22+15-2+deb8u2 => 5.22+15-2+deb8u3)
-    libmysqlclient18 (5.5.52-0+deb8u1 => 5.5.57-0+deb8u1)
-    libnettle4 (2.7.1-5+deb8u1 => 2.7.1-5+deb8u2)
-    libonig2 (5.9.5-3.2 => 5.9.5-3.2+deb8u1)
-    libpam-modules (1.1.8-3.1+deb8u1+b1 => 1.1.8-3.1+deb8u2+b1)
-    libpam-modules-bin (1.1.8-3.1+deb8u1+b1 => 1.1.8-3.1+deb8u2+b1)
-    libpam-runtime (1.1.8-3.1+deb8u1 => 1.1.8-3.1+deb8u2)
-    libpam-systemd (215-17+deb8u5 => 215-17+deb8u7)
-    libpam0g (1.1.8-3.1+deb8u1+b1 => 1.1.8-3.1+deb8u2+b1)
-    libperl5.20 (5.20.2-3+deb8u6 => 5.20.2-3+deb8u8)
-    libpng12-0 (1.2.50-2+deb8u2 => 1.2.50-2+deb8u3)
-    librtmp1 (2.4~20150315.gita107cef9b-dmo1 => 2.4~20150315.gita107cef9b-dmo1+deb8u2)
-    libss2 (1.42.12-2 => 1.42.12-2+b1)
-    libssl-dev (1.0.1t-1+deb8u5 => 1.0.1t-1+deb8u6)
-    libssl-doc (1.0.1t-1+deb8u5 => 1.0.1t-1+deb8u6)
-    libssl1.0.0 (1.0.1t-1+deb8u5 => 1.0.1t-1+deb8u6)
-    libsvn1 (1.8.10-6+deb8u4 => 1.8.10-6+deb8u5)
-    libsystemd0 (215-17+deb8u5 => 215-17+deb8u7)
-    libtasn1-6 (4.2-3+deb8u2 => 4.2-3+deb8u3)
-    libtiff5 (4.0.3-12.3+deb8u1 => 4.0.3-12.3+deb8u4)
-    libtirpc1 (0.2.5-1 => 0.2.5-1+deb8u1)
-    libudev1 (215-17+deb8u5 => 215-17+deb8u7)
-    libunbound2 (1.4.22-3+deb8u2 => 1.4.22-3+deb8u3)
-    libvarnishapi1 (4.0.2-1 => 4.0.2-1+deb8u1)
-    libxml2 (2.9.1+dfsg1-5+deb8u3 => 2.9.1+dfsg1-5+deb8u5)
-    libxpm4 (3.5.11-1+b1 => 3.5.12-0+deb8u1)
-    libxslt1.1 (1.1.28-2+deb8u1 => 1.1.28-2+deb8u3)
-    linux-image-3.16.0-4-amd64 (3.16.36-1+deb8u2 => 3.16.43-2+deb8u3)
-    linux-libc-dev (3.16.36-1+deb8u2 => 3.16.43-2+deb8u3)
-    locales (2.19-18+deb8u6 => 2.19-18+deb8u10)
-    login (4.2-3+deb8u1 => 4.2-3+deb8u4)
-    memcached (1.4.21-1.1 => 1.4.21-1.1+deb8u1)
-    minicom (2.7-1 => 2.7-1+deb8u1)
-    multiarch-support (2.19-18+deb8u6 => 2.19-18+deb8u10)
-    munin-common (2.0.25-1 => 2.0.25-1+deb8u3)
-    munin-node (2.0.25-1 => 2.0.25-1+deb8u3)
-    munin-plugins-core (2.0.25-1 => 2.0.25-1+deb8u3)
-    munin-plugins-extra (2.0.25-1 => 2.0.25-1+deb8u3)
-    mysql-common (5.5.52-0+deb8u1 => 5.5.57-0+deb8u1)
-    nodejs (0.12.17-1nodesource1~jessie1 => 0.12.18-1nodesource1~jessie1)
-    openssl (1.0.1t-1+deb8u5 => 1.0.1t-1+deb8u6)
-    os-prober (1.65 => 1.65+deb8u1)
-    passwd (4.2-3+deb8u1 => 4.2-3+deb8u4)
-    perl (5.20.2-3+deb8u6 => 5.20.2-3+deb8u8)
-    perl-base (5.20.2-3+deb8u6 => 5.20.2-3+deb8u8)
-    perl-modules (5.20.2-3+deb8u6 => 5.20.2-3+deb8u8)
-    php5 (5.6.26+dfsg-0+deb8u1 => 5.6.30+dfsg-0+deb8u1)
-    php5-cli (5.6.26+dfsg-0+deb8u1 => 5.6.30+dfsg-0+deb8u1)
-    php5-common (5.6.26+dfsg-0+deb8u1 => 5.6.30+dfsg-0+deb8u1)
-    php5-fpm (5.6.26+dfsg-0+deb8u1 => 5.6.30+dfsg-0+deb8u1)
-    php5-readline (5.6.26+dfsg-0+deb8u1 => 5.6.30+dfsg-0+deb8u1)
-    postfix (2.11.3-1 => 2.11.3-1+deb8u2)
-    python-crypto (2.6.1-5+b2 => 2.6.1-5+deb8u1)
-    python3-bottle (0.12.7-1 => 0.12.7-1+deb8u2)
-    python3-crypto (2.6.1-5+b2 => 2.6.1-5+deb8u1)
-    rdnssd (1.0.1-1+b1 => 1.0.1-1+deb8u1)
-    rpcbind (0.2.1-6+deb8u1 => 0.2.1-6+deb8u2)
-    rtmpdump (2.4~20150315.gita107cef9b-dmo1 => 2.4~20150315.gita107cef9b-dmo1+deb8u2)
-    sed (4.2.2-4+b1 => 4.2.2-4+deb8u1)
-    subversion (1.8.10-6+deb8u4 => 1.8.10-6+deb8u5)
-    systemd (215-17+deb8u5 => 215-17+deb8u7)
-    systemd-sysv (215-17+deb8u5 => 215-17+deb8u7)
-    tar (1.27.1-2+b1 => 1.27.1-2+deb8u1)
-    tcpdump (4.6.2-5+deb8u1 => 4.9.2-1~deb8u1)
-    tzdata (2016f-0+deb8u1 => 2017b-0+deb8u1)
-    udev (215-17+deb8u5 => 215-17+deb8u7)
-    unbound (1.4.22-3+deb8u2 => 1.4.22-3+deb8u3)
-    unbound-anchor (1.4.22-3+deb8u2 => 1.4.22-3+deb8u3)
-    unzip (6.0-16+deb8u2 => 6.0-16+deb8u3)
-    uwsgi (2.0.7-1 => 2.0.7-1+deb8u1)
-    uwsgi-core (2.0.7-1 => 2.0.7-1+deb8u1)
-    uwsgi-plugin-python (2.0.7-1 => 2.0.7-1+deb8u1)
-    vim (7.4.488-7 => 7.4.488-7+deb8u3)
-    vim-common (7.4.488-7 => 7.4.488-7+deb8u3)
-    vim-runtime (7.4.488-7 => 7.4.488-7+deb8u3)
-    vim-tiny (7.4.488-7 => 7.4.488-7+deb8u3)
-    w3m (0.5.3-19 => 0.5.3-19+deb8u2)
-    wget (1.16-1+deb8u1 => 1.16-1+deb8u2)
-    xsltproc (1.1.28-2+deb8u1 => 1.1.28-2+deb8u3)

151 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by Arcopix** [comment]
Syslog and arpwatch were cleaned up

**Comment by zeridon** [comment]
Updated configuration for first pass
