### ISSUE TITLE
Услуги на eric чиято конфигурация трябва да се провери

### ISSUE THREAD

**Issue by zeridon** [OpenFest/openfest-network-2017#9]
Да се спрат, провеерят и конфигурират както е необходимо
 - [x] collectd
 - [x] carbon-cache
 - [x] carbon-aggredator
 - [ ] munin-node
 - [x] uwsgi
 - [x] php-fpm
 - [x] fcgiwrap
 - [x] nginx
 - [ ] apache2
 - [x] arpwatch
 - [x] grafana
 - [x] ffmpeg
 - [x] nagios
 - [x] unbound
 - [x] isc-dhcpd
 - [x] radvd
 - [x] asterisk
 - [x] mumble
 - [x] fail2ban

**Comment by robotpanic** [comment]
Добавих и това, което инсталирах миналата година и беше репликирано също така на ерик2 - fail2ban. Работи си и е филтрирало вече доста "навлеци"  махнете го, ако не се връзва с "issue"-то: 

root@eric2:/etc/fail2ban # iptables -n -L fail2ban-ssh | wc -l
286
root@eric2:/etc/fail2ban #
